version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: niw_exercise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - mynetwork

#  springbootapp:
#    image: spring-niw_exercise:latest
#    container_name: springboot-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    networks:
#      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db:
    driver: local

