logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.raoliveira.imechanic: DEBUG

server:
  port: 8080

spring:
  application:
    name: '@name@'
  profiles:
    active: '@spring.profiles.active@'

  output:
    ansi:
      enabled: always

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/niw_exercise

  # JPA
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      database: postgresql
      hibernate:
        hbm2dll:
          create_namespaces: true
        format_sql: true
        default_schema: public